contacts = {
'Markus Thill': 'markus.thill at th-koeln.de',
'Marco Scirea': 'marco.prolog@gmail.com',
'SEBASTIAN DETERDING': 'sebastian.deterding@york.ac.uk',
'Craig W. Smith': 'csmith@oakland.edu',
'C. Bessiere': 'bessiere@lirmm.fr',
'Keisha VARMA': 'keisha@umn.edu',
'Belanger, David': 'dave@dave.ucsc.edu',
'Dimitris Paleothodoros': 'palaio@uth.gr',
'EUNJUNG CHO': 'echoi@claflin.edu',
'Eko Nugroho': 'studio.ekonugroho@gmail.com',
'Jon-Chao, Hong': 'tcdahong@gmail.com',
'Simone Mora': 'simone.mora@idi.ntnu.no',
'Ulrich Schädler': 'schaedler.u@bluewin.ch',
'Javier Olivito': 'javier@apiolivito.com',
'Douglas Brown': 'Douglas.Brown@uc.edu',
'Moreau, Katherine': 'kmoreau@uottawa.ca',
'Adam Brown': 'adam.brown@deakin.edu.au',
'Barbara Carè': 'bc.barbara.care@gmail.com',
'Adam Brown': 'adam.brown@deakin.edu.au',
'Denis Robilliard': 'denis.robilliard@lisic.univ-littoral.fr',
'Jakub Kowalski': 'jko@cs.uni.wroc.pl',
'A. Juhász': 'Juhasz.Adam@stud.u-szeged.hu',
'Khaled Rasheed': 'khaled@uga.edu',
'Tatiana V. Evreinova': 'Tatiana.V.Evreinova@uta.fi',
'Timothy Harding': 'tim.harding@dlapiper.com',
'Javier Marco': 'jmarco2000@gmail.com',
'MILENE SELBACH SILVEIRA': 'milene.silveira@pucrs.br',
'Nicholson, Scott': 'scott@scottnicholson.com',
'Maija Vanhala': 'Maija.vanhala@laurea.fi',
'Wu Chen': 'chenwu@swu.edu.cn',
'Umair Ahmed': 'umair.ahmed@ncl.ac.uk',
'Dale Purves': 'purves@neuro.duke.edu',
'Vera Novikova': 'veranovikova@sibmail.com',
'Mareike Bockholt': 'mareike.bockholt@cs.uni-kl.de',
'Francesca Pozzi': 'francesca.pozzi@itd.cnr.it',
'Ayla Cetin-Dindar': 'adindar@bartin.edu.tr',
'Michael Horn': 'michael-horn@northwestern.edu',
'Bahar Kutun': 'Bahar.Kutun@thi.de',
'Bethan Jones': 'Bethan.Jones@liverpool.ac.uk',
'Alexander J. de Voogt': 'adevoogt@amnh.org',
'Jens Jahnke': 'jjahnke@balderip.com',
'Shalini Kurapati': 'S.Kurapati@tudelft.nl',
'Rico Möckel': 'rico.mockel@maastrichtuniversity.nl',
'Jan Alexandersson': 'jan.alexandersson@dfki.de',
'Marja Kankaanranta': 'marja.kankaanranta@jyu.fi',
'Evgeny Stemasov': 'evgeny.stemasov@uni-ulm.de',
'Laura Bofferding': 'lbofferd@purdue.edu',
'Krystof Kozak': 'kkozak@scio.cz',
'Thierry Depaulis': 'thierry.depaulis@free.fr',
'Penny Singh': 'pennysinghstudio@gmail.com',
'Alex de Voogt': 'adevoogt@amnh.org',
'Dale E. Parson': 'parson@kutztown.edu',
'John Romein': 'john@cs.vu.nl',
'Dempsey, John V': 'jdempsey@usouthal.edu',
'María Jesús Inostroza Araos': 'minostrozaa@udec.cl',
'Jiajia Zhang': 'jzhang@mailbox.sc.edu',
'Sam Ingleson': 'S.J.Ingleson@salford.ac.uk',
'Hui Li, Ph.D.': 'lilab.medicine.virginia.edu',
'Antonio Gonzalez-Pardo': 'gr_inv.grafo@urjc.es',
'Alex de Voogt': 'adevoogt@amnh.org',
'Dina Nurhayati': 'muhammad.dzikri@bankmuamalat.co.id',
'Fátima Monteiro': 'fatcmont@isec.pt',
'John Gough': 'jug@aber.ac.uk',
'Tom Burns': 'thomas.burns@oist.jp',
'Huy Nguyen': 'nqhuy@sgu.edu.vn',
'Priyan L. Jayamaha': 'priyanj@yahoo.com',
'Eva Brandt': 'eva.brandt@dkds.dk',
'Allen Glenn': 'aglenn@uw.edu',
'Tharrenos Bratitsis': 'bratitsis@uowm.gr',
'Francisco J. Rodr´ıguez–Sedano': 'francisco.sedano@unileon.es',
'Fika Widya Pratama': 'fika.pratama@uksw.edu',
'Kazuhisa Yanaka': 'yanaka@ic.kanagawa-it.ac.jp',
'Víctor Gonzalo-Cristóbal': 'uo264074@uniovi.es',
'Parlindungan Siregar': 'parlins@uinjkt.ac.id',
'Jorge Nuno Silva': 'jnsilva@cal.berkeley.edu',
'Fulvio Frapolli': 'Fulvio.Frapolli@gmail.ch',
'Chong-Wen Chen': 'cwchen@mail.ntust.edu.tw',
'Mark A. Hall': 'hallma@wfu.edu',
'Lyudmila V Yakhnis Mail': 'myakhnis@yahoo.com',
'Montchatry Ketmuni': 'montchatry@rmutt.ac.th',
'B. Mitschang': 'mitschang@informatik.uni-stuttgart.de',
'Li-Jen Liu': 'liulijen@gmail.com',
'Irving L. Finkel': 'middleeast@britishmuseum.org',
'Nurmukhamedov, Ulugbek': 'u-nurmukhamedov@neiu.edu',
'Verhaegh PhD': 'A.A.Verhaegh@tilburguniversity.edu',
'Mohd Kamal Othman': 'kmothman1400@gmail.com',
'Alex Moseley': 'alex.moseley@aru.ac.uk',
'Vlada Krainikova': 'vakraynikova@edu.hse.ru',
'Benjamin D. Douglas': 'bdouglas3@wisc.edu',
'Ni Made Ratminingsih': 'made.ratminingsih@undiksha.ac.id',
'A. Vahed': 'anisav@dut.ac.za',
'Sean Cavanagh': 'scavanagh@epe.org',
'Ricardo Simões': 'ramb@amb.org.br',
'Jorge Nuno Silva': 'jnsilva@cal.berkeley.edu',
'Wozny, Cecilia': 'ceciliafiore@uda.edu.ar',
'Thorsten Prante': 'prante@ipsi.fraunhofer.de',
'Tanja Munz': 'contact@tanjamunz.de',
'Hye Sun Lee': 'hye.lee@cms.hhs.gov',
'Dhika Yuan Yurisma': 'dxx@dinamika.ac.id',
'H. Almås': 'havard.almas@hoknowledge.com',
'Heide Lukosch': 'H.K.Lukosch@tudelft.nl',
'Alex de Voogt': 'adevoogt@amnh.org',
'Thompson, Kara Patrice': 'kara.thompson@colostate.edu',
'Liv Helene Willumsen': 'liv.h.willumsen@uit.no',
'Kelli Wood': 'kwood29@utk.edu',
'Sullivan, Anne': 'Anne.Sullivan@ucf.edu',
'Frincy Francis': 'frincyshalom@gmail.com',
'Nathalie Charlier PhD': 'nathalie.charlier@pharm.kuleuven.be',
'Hideaki Ogawa': 'hideaki.ogawa@rmit.edu.au',
'Brian Magerko': 'magerko@gatech.edu',
'Lu, Chow-Chin': 'luchowch@tea.ntue.edu.tw',
'Michael Heron': 'heronm@chalmers.se',
'Heather Desurvire': 'heather3d@gmail.com',
'Natalie Underberg-Goode': 'Natalie.Underberg-Goode@ucf.edu',
'Giorgio Gnecco': 'giorgio.gnecco@imtlucca.it',
'Kemachart Kemavuthanon': 'kemachart.kem@mfu.ac.th',
'Hans-Joachim Backe': 'hanj@itu.dk',
'Erich Neuhold': 'neuhold@ipsi.fraunhofer.de',
'Fabio Chiarello': 'fabio.chiarello@ifn.cnr.it',
'Bull, Rebecca': 'bull@mq.edu.au',
'Y. Juahir': 'yusnita@fsmt.upsi.edu.my',
'Tristan Cazenave': 'cazenave@lamsade.dauphine.fr',
'Paulo Antunes': 'p.antunes@cscestrie.on.ca',
'Sirin Guney Ozenc': 'ozenc@tau.edu.tr',
'Blanka Frydrychova Klimova': 'blanka.klimova@uhk.cz',
'Andrew D. Wilson': 'awilson@microsoft.com',
'Wiśniewska-Grabarczyk, Anna': 'anna.wisniewska-grabarczyk@filologia.uni.lodz.pl',
'Widya Syafitri': 'widyasyafitri@uinbukittinggi.ac.id',
'N.John Habraken': 'john@habraken.org',
'Tristan Cazenave': 'cazenave@ai.univ-paris8.fr',
'Cameron Browne': 'cambrowne@louisiana.edu',
'Eddie Duggan': 'e.duggan@uos.ac.uk',
'Tarun Khanna': 'tkhanna@hbs.edu',
'Ting-Chia Hsu': 'ckhsu@ntnu.edu.tw',
'Hind Abdulmajed': 'habdulmajed@kau.edu.sa',
'Markku Eskelinen': 'markku.eskelinen@eskelinenlaki.fi',
'Riccardo Martoglia': 'riccardo.martoglia@unimore.it',
'Jonne Arjoranta': 'jonne.arjoranta@jyu.fi',
'Shanming Loh': 'shanming.loh@gmail.com',
'Cameron Browne': 'cambrowne@louisiana.edu',
'Norhayati Norhayati': 'norhayati@kpju.edu.my',
'Fox, Helen': 'helen.fox@stonybrookmedicine.edu',
'Tapani Raiko': 'Tapani.Raiko@tkk.fi',
'Éric Piette': 'eric.piette@uclouvain.be',
'M N R Jauhariyah': 'mukhayyarotinjauhariyah@unesa.ac.id',
'Micael Sousa': 'micaelssousa@gmail.com',
'Jakub Kowalski': 'jko@cs.uni.wroc.pl',
'Michael Barbour': 'mkbarbour@gmail.com',
'Chi Tai Dang': 'dang@informatik.uni-augsburg.de',
'Hiroyuki Iida': 'hiroyuki.iida@helsinki.fi',
'Jason Begy': 'jsbegy@mit.edu',
'Vukosi N. Marivate': 'vukosi.marivate@cs.up.ac.za',
'Md. Abdullah-Al-Mahmud': 'mahmud@bsmrau.edu.bd',
'Heather Lotherington': 'hlotherington@edu.yorku.ca',
'Jonny B. Pornel': 'jonnybpornel@yahoo.com',
'Joris Dormans': 'j.dormans@hum.leidenuniv.nl',
'Sadia Shaikh': 'dr.sadiashaikh@bbsul.edu.pk',
'Dr. Fivos Papadimitriou': 'fivos.papadimitriou@mnf.uni-tuebingen.de',
'Nima Asemani Barekat': 'nimaac1380@gmail.com',
'Simon M. Lucas': 'simon.lucas@qmul.ac.uk',
'Geraldo Xexéo': 'xexeo@cos.ufrj.br',
'María González-Miquel': 'maria.gonzalezmiquelupm.es',
'Theresa-Marie Rhyne': 'theresamarierhyne@gmail.com',
'Barry D Mann M.D.': 'barry.mann@drexel.edu',
'Patrick Jagoda': 'pjagoda@uchicago.edu',
'Ting-Chia Hsu': 'ckhsu@ntnu.edu.tw',
'Hillbom, Niklas': 'niklas.hillbom@klass.lu.se',
'Baldanza, Ben': 'bbaldanz@gmu.edu',
'Ting-Chia Hsu': 'ckhsu@ntnu.edu.tw',
'Christina Köffel': 'christina.koeffel@fh-hagenberg.at',
'Alan Barson': 'abarson@taylorenglish.com',
'Eddie Duggan': 'e.duggan@uos.ac.uk',
'Hannah Smith': 'hsmith2@wpi.edu',
'Jung Younbo': 'ybjung@ntu.edu.sg',
'Peter Ganz, MD': 'peter.ganz@ucsf.edu',
'Sonia Chiasson': 'farah.chanchary@carleton.ca',
'Lukasz Kaiser': 'kaiser@liafa.jussieu.fr',
'Karl Kronkvist': 'karl.kronkvist@mau.se',
'Safiani binti Osman': 'safiani@pms.edu.my',
'Wen Liang': 'lai@mail.tajen.edu.tw',
'Robyn Hromek': 'robyn.hromek@det.nsw.edu.au',
'Katerina Tsarava': 'k.tsarava@iwm-tuebingen.de',
'Dores Ferreira': 'jessferreira625@hotmail.com',
'Jennifer J. Salopek': 'jjsalopek@cox.net',
'Marianne P. Celano': 'mcelano@emory.edu',
'Gina Nurpalah': 'ginanurpalah31@gmail.com1',
'James R. Coakley': 'coakley@bus.orst.edu',
'Barbara Voorhies': 'voorhies@anth.ucsb.edu',
'Alex de Voogt': 'adevoogt@amnh.org',
'Frank Hoffmann': 'Frank.Hoffmann@uni-hamburg.de',
'Restu Hendriyani Magh firoh': 'restu@ikado.ac.id',
'Cameron Browne': 'cambrowne@louisiana.edu',
'Thomas R. Hinrichs': 'T-HINRICHS@NORTHWESTERN.EDU',
'Antonios Liapis': 'an.liapis@gmail.com',
'Dr. Nosheen Sabahat': 'nosheensabahat@fccollege.edu.pk',
'Denis S. Artamonov': 'artamonovds@mail.ru',
'Andreas Lieberoth': 'andreas@psy.au.dk',
'Xiaoping Hu': 'xhu@bme.emory.edu',
'G. Kendall': 'graham.kendall@nottingham.edu.my',
'Roger Smith': 'roger.smith14@us.army.mil',
'L.J.A. Lipman': 'l.j.a.lipman@uu.nl',
'Hiroyuki Iida': 'iida@jaist.ac.jp',
'Patrick Koch': 'patrick.benjamin.koch@uni-hamburg.de',
'Mark R. Dixon': 'mdixon@siu.edu',
'Gwo-Jen Hwang': 'gjhwang.academic@gmail.com',
'Jakub Kowalski': 'jko@cs.uni.wroc.pl',
'Annika Waern': 'annika.waern@im.uu.se',
'Linda Haynes': 'linda.haynes@marquette.edu',
'Irene Celino': 'irene.celino@cefriel.it',
'Louis D’Alotto': 'ldalotto@york.cuny.edu',
'Mark Blyth': 'mark_blyth@brown.edu',
'Charles Lovering': 'Charles.Lovering@brown.edu',
'Mary Bendixen-Noe': 'bendixen-noe.1@osu.edu',
'Maria Tsapara Bratitis': 'bratitsis@uowm.gr',
'S.C. Althoen': 'althoen@ualberta.ca',
'Kyle J. Burghardt Pharm.D.': 'kburg@umich.edu',
'Cassie, Jonathan': 'joncassie@gmail.com',
'Divya Menon': 'divya_menon@emerson.edu',
'Michael Buro': 'mburo@cs.ualberta.ca',
'Ville Kankainen': 'ville.kankainen@tuni.fi',
'María Begoña Martos-Cabrera': 'mbmartos@ujaen.es',
'Browne, Cameron Bolitho': 'cameron.browne@btinternet.com',
'Cécile Swiatek': 'cecile.swiatek@gmail.com',
'Geraldo Xexéo': 'xexeo@cos.ufrj.br',
'Paivi Marjanen': 'paivi.marjanen@laurea.fi',
'Alex de Voogt': 'adevoogt@amnh.org',
'Darja Kragić Kok': 'd.kragic@nwp.nl',
'Cedric K. W. Tan': 'Cedric.Tan@nottingham.edu.my',
'Sufen Chen': 'sufchen@mail.ntust.edu.tw',
'Baranyai, Tünde': 'tunde.baranyai@ubbcluj.ro',
'Andrew Topsfield': 'andrew.topsfield@ashmus.ox.ac.uk',
'Jialin Liu': 'jialin.liu.cn@gmail.com',
'Christiane Gresse von Wangenheim': 'c.wangenheim@ufsc.br',
'Paulo Eduardo Battistella': 'paulo@incod.ufsc.br',
'T. Atilla Ceranoglu': 'aceranoglu@partners.org',
'Elise van den Hoven': 'e.v.d.hoven@tue.nl',
'Marcin Szubert': 'Marcin.Szubert@cs.put.poznan.pl',
'Geertje Bekebrede': 'g.bekebrede@tudelft.nl',
'Joey J. Lee': 'jl3471@tc.columbia.edu',
'Kasper Røjkjær Andersen': 'kra@mbg.au.dk',
'Hedwig Gasteiger': 'hedwig.gasteiger@mathematik.uni-muenchen.de',
'Yolanda Taneva Rahmi': 'rekamakna@itenas.ac.id',
'Rafael Savi': 'rafaelsavi@gmail.com',
'Femy Rahmadani': 'femirahma19@gmail.com',
}
